import type { Metadata } from "next";
import { sans, mont } from "@/app/ui/fonts"
import Navbar from '@/app/components/navbar/navbar'
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans.variable} ${mont.variable} flex min-h-screen flex-col items-center justify-between bg-gray-20`}>
        {children}
        </body>
    </html>
  );
}
